name: GitHub Rate Limit Alert (Graph API)

on:
  schedule:
    - cron: "*/30 * * * *"  # run every 30 min
  workflow_dispatch:

jobs:
  check-rate-limit:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.RSA_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Check GitHub Rate Limit
        id: rate_limit
        run: |
          curl -s -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
               -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/rate_limit > rate.json

          REMAINING=$(jq '.rate.remaining' rate.json)
          echo "Remaining: $REMAINING"
          echo "rate_remaining=$REMAINING" >> $GITHUB_OUTPUT

      - name: Get Microsoft Graph Token
        id: graph_token
        run: |
          RESPONSE=$(curl -s -X POST https://login.microsoftonline.com/${{ secrets.TENANT_ID }}/oauth2/v2.0/token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}&scope=https://graph.microsoft.com/.default")

          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Send Email if Low
        if: steps.rate_limit.outputs.rate_remaining != '' && steps.rate_limit.outputs.rate_remaining <= 500
        run: |
          curl -X POST https://graph.microsoft.com/v1.0/users/${{ secrets.MAIL_FROM }}/sendMail \
            -H "Authorization: Bearer ${{ steps.graph_token.outputs.token }}" \
            -H "Content-Type: application/json" \
            -d '{
              "message": {
                "subject": "GitHub Rate Limit Alert",
                "body": {
                  "contentType": "Text",
                  "content": "⚠️ GitHub API rate limit is running low.\n\nRemaining calls: '${{ steps.rate_limit.outputs.rate_remaining }}'\n\nPlease investigate your workflows."
                },
                "toRecipients": [
                  {
                    "emailAddress": {
                      "address": "'${{ secrets.MAIL_TO }}'"
                    }
                  }
                ]
              }
            }'
